// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsOeW9U37YTnoa0-8pM-EyxV2SXzIteSI',
    appId: '1:302884111160:web:0ed732cd7ecc7b4a3577cd',
    messagingSenderId: '302884111160',
    projectId: 'new-project3-b123c',
    authDomain: 'new-project3-b123c.firebaseapp.com',
    storageBucket: 'new-project3-b123c.firebasestorage.app',
    measurementId: 'G-167PTRSCWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8ahiPUFlgeBYe35UsnyHpgna8S_o2qM',
    appId: '1:302884111160:android:959625c976af3ad13577cd',
    messagingSenderId: '302884111160',
    projectId: 'new-project3-b123c',
    storageBucket: 'new-project3-b123c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGLGyQSUGGx2d8tOd-9okqtLxi7IOxhDg',
    appId: '1:302884111160:ios:e1c5a237f2c2f99a3577cd',
    messagingSenderId: '302884111160',
    projectId: 'new-project3-b123c',
    storageBucket: 'new-project3-b123c.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGLGyQSUGGx2d8tOd-9okqtLxi7IOxhDg',
    appId: '1:302884111160:ios:e1c5a237f2c2f99a3577cd',
    messagingSenderId: '302884111160',
    projectId: 'new-project3-b123c',
    storageBucket: 'new-project3-b123c.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsOeW9U37YTnoa0-8pM-EyxV2SXzIteSI',
    appId: '1:302884111160:web:a56ec1522ab391973577cd',
    messagingSenderId: '302884111160',
    projectId: 'new-project3-b123c',
    authDomain: 'new-project3-b123c.firebaseapp.com',
    storageBucket: 'new-project3-b123c.firebasestorage.app',
    measurementId: 'G-B7CS003M6D',
  );
}
